# Generated by Django 5.2.17 on 2026-09-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cliente_proveedor_venta_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la oferta', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o condiciones breve', null=True)),
                ('imagen', models.ImageField(help_text='Imagen del banner publicitario', upload_to='ofertas/')),
                ('activo', models.BooleanField(default=True, help_text='Marcar para mostrar en el login')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor a mayor)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ofertas_slider',
                'ordering': ['orden', '-creado_en'],
            },
        ),
    ]
